name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

env:
  Xcode_Version: 26.2

jobs:
  mobile:
    strategy:
      matrix:
        os: [macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    # Install .NET SDK
    - name: Setup .NET 10.0.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x' # Adjust to your required .NET SDK version

    - name: Install .NET MAUI
      run: 'dotnet workload install maui'

    - name: Install Xcode
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.Xcode_Version }}

    - name: Display .NET Info
      run: 'dotnet --info'  

    - name: Build HackerNews
      run: |
        cd "4. .NET Internals/4. SynchronizationContext"
        dotnet build